services:
  - type: web
    name: n8n
    env: docker
    region: oregon  # Optional (defaults to oregon)
    plan: standard  # Optional (defaults to starter)
    branch: main  # Optional (defaults to master)
    numInstances: 1
    healthCheckPath: /
    disk:
      name: n8nDisk
      mountPath: /home/node/.n8n  # Ensures SQLite data persists
      sizeGB: 10  # Adjust as needed
